USE Library_Drill;

CREATE PROCEDURE dbo.Library_Query_Drill

AS

SELECT Title, No_Of_Copies, BranchName FROM dbo.BOOK_COPIES
INNER JOIN BOOK ON BOOK_COPIES.BookID = BOOK.BookID
INNER JOIN LIBRARY_BRANCH ON BOOK_COPIES.BranchID = LIBRARY_BRANCH.BranchID
WHERE Title = 'The Lost Tribe' AND BranchName = 'Sharpstown'
;

SELECT Title, No_Of_Copies, BranchName FROM dbo.BOOK_COPIES
INNER JOIN BOOK ON BOOK_COPIES.BookID = BOOK.BookID
INNER JOIN LIBRARY_BRANCH ON BOOK_COPIES.BranchID = LIBRARY_BRANCH.BranchID
WHERE Title = 'The Lost Tribe'
;

SELECT Name FROM dbo.BORROWER
FULL OUTER JOIN BOOK_LOANS ON BORROWER.CardNo = BOOK_LOANS.CardNo
WHERE BOOK_LOANS.CardNo IS NULL
;

SELECT Title AS 'Book Title', Name AS 'Borrower Name', BORROWER.Address AS 'Borrower Address' FROM BOOK_LOANS
INNER JOIN BOOK ON BOOK_LOANS.BookID = BOOK.BookID
INNER JOIN BORROWER ON BOOK_LOANS.CardNo = BORROWER.CardNo
INNER JOIN LIBRARY_BRANCH ON BOOK_LOANS.BranchID = LIBRARY_BRANCH.BranchID
WHERE LIBRARY_BRANCH.BranchName = 'Sharpstown' AND DueDate = '20170922'
;

SELECT BranchName AS 'Branch Name', COUNT(LoansID) AS 'Books On Loan' FROM BOOK_LOANS
INNER JOIN LIBRARY_BRANCH ON BOOK_LOANS.BranchID = LIBRARY_BRANCH.BranchID
Group By BranchName;

SELECT BORROWER.Name AS 'Borrower Name', BORROWER.Address AS 'Borrower Address', COUNT(LoansID) AS 'Books On Loan' FROM BORROWER
INNER JOIN BOOK_LOANS ON BORROWER.CardNo = BOOK_LOANS.CardNo
Group By BORROWER.Name, BORROWER.ADDRESS
HAVING COUNT(LoansID) >= 5
;

SELECT Title AS 'Book Title', No_Of_Copies AS 'Number of Copies'FROM BOOK_COPIES
INNER JOIN BOOK ON BOOK_COPIES.BookId = BOOK.BookId
INNER JOIN LIBRARY_BRANCH ON BOOK_COPIES.BranchID = LIBRARY_BRANCH.BranchID
INNER JOIN BOOK_AUTHORS ON BOOK_COPIES.BookID = BOOK_AUTHORS.BookID
WHERE AuthorName = 'King, Stephen' AND BranchName = 'Central'
;